services:

  api-gateway:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: api-gateway
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - backend/.env
    depends_on:
      postgres:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: dtt
      POSTGRES_USER: dtt
      POSTGRES_PASSWORD: dttdttdtt
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dtt -d dtt" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  redis:
    image: redis
    container_name: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - ./config/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf